### ISSUE TITLE
Install the package without nuget, just using snadmin?

### ISSUE THREAD

**Issue by swacsa** [SenseNet/sn-adsync#1]
I haven't found any description how to install the package using the snadmin instead of nuget and VS. 
Is there any way to do it - like knowledgebase?

**Comment by tusmester** [comment]
Currently that is not supported, all our components are published through NuGet, mainly because usually there are dlls or other source code elements involved that need to be added to the VS project.

**Comment by swacsa** [comment]
ok, thanks, I close this issue.
