### ISSUE TITLE
install-syncad2portal  failed with does not allow type...

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-adsync#2]
@marosvolgyiz commented on [Mon Sep 16 2019](https://github.com/SenseNet/sensenet/issues/677)

Hi, 

I installed Sensenet Services 7.6.1.

I tried to install syncad2portal from nuget. The packege is downloaded, and the code is built succesfully. When I try to install with snadmin, I get the following error:
[install_adsync_issue](https://user-images.githubusercontent.com/26160248/64939134-7c935080-d860-11e9-8808-b1b44d5ebd7c.png)

Br,
maros

**Comment by tusmester** [comment]
@marosvolgyiz This is probably caused by the fact that the import items in the adsync package assume that the root folders (Global, System, etc.) already exist as _system folders_. If this is not the case than these folders will be imported as _simple folders_. This results in an allowed child type error when installing the package, because a File cannot be uploaded there by default.

### Solution
Add a Content file next to the first level containers in the adsync package that defines them as system folders (we can copy these content files from the Services or WebPages packages).

**Comment by VargaJoe** [comment]
let me try this one :)
